# Super useful comment.
[config]
name = "fancy configuration name"
list = "game.exe util.exe"


[recipe]
name    = "executable"
parent  = "fancy configuration name"
pattern = "*.exe"
output  = "out/${file}"
objects = prepare "src/*.cc"
command = "clang++ -o ${output} ${objects}"


[recipe]
name    = "object file"
parent  = "executable program"
pattern = "src/*.cc"
output  = "obj/${file:name}.o"
command = "clang++ -o ${output} 'src/${file}'"